name: 检查电费并发送通知 
  
on:  
  schedule:  
    # 每1h运行一次  
    - cron: '0 */1 * * *'
    
  workflow_dispatch: 
  
jobs:  
  check-number-and-send-email:  
    runs-on: ubuntu-latest  
    env:  
      TZ: Asia/Shanghai # 设置时区为上海
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:  
      - name: 进入仓库  
        uses: actions/checkout@v4 
        
      - name: 安装依赖工具
        run: sudo apt-get install -y bc
          
      - name: 检查电费 
        id: check-number  
        run: |  
          RESPONSE=$(curl -s -H "User-Agent: Android 6.0" https://www.wap.cnyiot.com/nat/pay.aspx?mid=19500754882)
          # 提取电费数据
          NUMBER=$(echo "$RESPONSE" | grep -oP 'inline-block;">\K\d+\.\d+(?=</label> <span>元<)')
          
          # 检查提取结果
          if [ -z "$NUMBER" ]; then
            echo "无法提取电费数据"
            exit 1
          fi
          
          echo "当前电费: $NUMBER"  
          echo "电费提醒阈值: ${{ vars.ELECTRIC_NOTICE_VAL }}"
          echo "$(date +'%Y-%m-%d %H:%M'),$NUMBER" >> docs/data.csv
          
          # 判断电费是否不足
          if (( $(echo "$NUMBER < ${{ vars.ELECTRIC_NOTICE_VAL }}" | bc -l) )); then
            echo "send_email=true" >> $GITHUB_OUTPUT
            echo "number=$NUMBER" >> $GITHUB_OUTPUT
          else    
            echo "send_email=false" >> $GITHUB_OUTPUT
          fi
          
      - name: 提交变更  
        run: |  
          git config --local user.email "2013855675@qq.com"  
          git config --local user.name "sunl888"  
          git add docs/data.csv
          # 只有存在变更时才提交
          if git diff --cached --quiet; then
            echo "无数据变更，无需提交"
          else
            git commit -m "Update electricity bill data"
            git push
          fi
          
      - name: 发送电费不足通知  
        if: steps.check-number.outputs.send_email == 'true'  
        uses: dawidd6/action-send-mail@v3  
        with:  
          server_address: smtp.qq.com 
          server_port: 465 
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 电费不足提醒  
          to: ${{ secrets.TO_MAIL }}
          from: ${{ secrets.FROM_MAIL }} 
          body: | 
              你的电费已不足，请尽快充电: ${{ steps.check-number.outputs.number }}
