name: 检查电费并发送通知 
  
on:  
  schedule:  
    # 每1h运行一次  
    - cron: '0 */1 * * *'  
    
  workflow_dispatch: 
  
jobs:  
  check-number-and-send-email:  
    runs-on: ubuntu-latest  
    env:  
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 用于推送更改到GitHub仓库  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v2 
        
      - name: pull changes
        run: |   
          git pull  
          
      - name: 检查电费 
        id: check-number  
        run: |  
          RESPONSE=$(curl -s -H "User-Agent: Android 6.0" https://www.wap.cnyiot.com/nat/pay.aspx?mid=19500754882)
          NUMBER=$(echo $RESPONSE | grep -oP 'inline-block;">\K\d+\.\d+(?=</label> <span>元<)')
          echo "当前电费: $NUMBER"  
          echo "电费提醒阈值: ${{ vars.ELECTRIC_NOTICE_VAL }}"
          echo "$(date +'%Y-%m-%d %H:%M:%S'),$NUMBER" >> docs/data.csv
          
          # 判断电费是否不足
          if (( $(echo "$NUMBER < ${{ vars.ELECTRIC_NOTICE_VAL }}" | bc -l) )); then
            echo "send_email=true" >> $GITHUB_OUTPUT
            echo "number=$NUMBER" >> $GITHUB_OUTPUT
          else    
            echo "send_email=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push changes  
        run: |  
          git config --local user.email "2013855675@qq.com"  
          git config --local user.name "sunl888"  
          git commit -am "Update electricity bill data"  
          git push  
          
      - name: 发送电费不足通知  
        if: steps.check-number.outputs.send_email == 'true'  
        uses: dawidd6/action-send-mail@v3  
        with:  
          server_address: smtp.qq.com 
          server_port: 465 
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 电费不足提醒  
          to: ${{ secrets.TO_MAIL }}
          from: ${{ secrets.FROM_MAIL }} 
          body: | 
              你的电费已不足，请尽快充电: ${{ steps.check-number.outputs.number }}
              
